{
  "openapi": "3.0.0",
  "info": {
    "title": "dxWeb",
    "contact": {},
    "version": "1.0"
  },
  "servers": [
    {
      "url": "http://standalone.az-qa.com:81/dxweb/rest",
      "variables": {}
    }
  ],
  "paths": {
    "/customers": {
      "post": {
        "tags": [
          "Misc"
        ],
        "summary": "createCustomer",
        "operationId": "createCustomer",
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "application/x-www-form-urlencoded"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/x-www-form-urlencoded": {
              "encoding": {},
              "schema": {
                "required": [
                  "email",
                  "password",
                  "currencyCode",
                  "accountType",
                  "brandPrefix",
                  "activeStatus",
                  "company",
                  "fullName",
                  "isIslamic",
                  "isPaperMoney",
                  "isOmnibus",
                  "country"
                ],
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string",
                    "example": "nastya2211@test.ua"
                  },
                  "password": {
                    "type": "integer",
                    "format": "int32",
                    "example": 123
                  },
                  "currencyCode": {
                    "type": "string",
                    "example": "USD"
                  },
                  "accountType": {
                    "type": "string",
                    "example": "REAL"
                  },
                  "brandPrefix": {
                    "type": "string",
                    "example": "si"
                  },
                  "activeStatus": {
                    "type": "integer",
                    "format": "int32",
                    "example": 1
                  },
                  "company": {
                    "type": "string",
                    "example": "strongbow"
                  },
                  "fullName": {
                    "type": "string",
                    "example": "nastya"
                  },
                  "isIslamic": {
                    "type": "integer",
                    "format": "int32",
                    "example": 0
                  },
                  "isPaperMoney": {
                    "type": "integer",
                    "format": "int32",
                    "example": 0
                  },
                  "isOmnibus": {
                    "type": "integer",
                    "format": "int32",
                    "example": 0
                  },
                  "country": {
                    "type": "string",
                    "example": "ua"
                  }
                }
              },
              "examples": {
                "JSON": {
                  "summary": "JSON",
                  "value": {
                    "email": "nastya2211@test.ua",
                    "password": "123",
                    "currencyCode": "USD",
                    "accountType": "REAL",
                    "brandPrefix": "mk",
                    "activeStatus": "1",
                    "company": "strongbow",
                    "fullName": "nastya",
                    "isIslamic": "0",
                    "isPaperMoney": "0",
                    "isOmnibus": "0",
                    "country": "ua"
                  }
                }
              }
            }
          },
          "required": false,
          "x-send-file-in-body": false
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "servers": [
          {
            "url": "http://standalone.az-qa.com:81/dxweb/rest",
            "variables": {}
          }
        ]
      }
    },
    "/customers/si10016300": {
      "put": {
        "tags": [
          "Misc"
        ],
        "summary": "updateAccount",
        "operationId": "updateAccount",
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "application/x-www-form-urlencoded"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/x-www-form-urlencoded": {
              "encoding": {},
              "schema": {
                "required": [
                  "newFullName",
                  "country",
                  "activeStatus"
                ],
                "type": "object",
                "properties": {
                  "newFullName": {
                    "type": "string",
                    "example": "Nastya"
                  },
                  "country": {
                    "type": "string",
                    "example": "fr"
                  },
                  "activeStatus": {
                    "type": "integer",
                    "format": "int32",
                    "example": 0
                  }
                }
              },
              "examples": {
                "JSON": {
                  "summary": "JSON",
                  "value": {
                    "activeStatus": "0",
                    "fullName": "Nastya",
                    "country": "fr"
                  }
                }
              }
            }
          },
          "required": false,
          "x-send-file-in-body": false
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "servers": [
          {
            "url": "http://standalone.az-qa.com:81/dxweb/rest",
            "variables": {}
          }
        ]
      }
    },
    "/customers/si10016300/transfers": {
      "post": {
        "tags": [
          "Misc"
        ],
        "summary": "changeAccountBalance",
        "operationId": "changeAccountBalance",
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "application/x-www-form-urlencoded"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/x-www-form-urlencoded": {
              "encoding": {},
              "schema": {
                "required": [
                  "amount",
                  "transferType",
                  "transferCode",
                  "comment",
                  "requestSource"
                ],
                "type": "object",
                "properties": {
                  "amount": {
                    "type": "integer",
                    "format": "int32",
                    "example": 100
                  },
                  "transferType": {
                    "type": "string",
                    "example": "DEPOSIT"
                  },
                  "transferCode": {
                    "type": "string",
                    "example": "AAABZzsI9ywwwRbkK_L"
                  },
                  "comment": {
                    "type": "string",
                    "example": "Comments"
                  },
                  "requestSource": {
                    "type": "string",
                    "example": "CRM"
                  }
                }
              },
              "examples": {
                "JSON": {
                  "summary": "JSON",
                  "value": {
                    "sessionCode": "COSMOS",
                    "quantity": 100.0,
                    "transferType": "DEPOSIT",
                    "comment": "Comments",
                    "actionCode": "1123",
                    "id": 41320324
                  }
                },
                "CURL": {
                  "summary": "CURL",
                  "value": "curl --location --request POST '{{domain}}/dxweb/rest/customers/Vasyl123/transfers' \\\n--header 'Content-Type: application/x-www-form-urlencoded' \\\n--header 'Authorization: Basic cm9vdEBzeXN0ZW06cm9vdA==' \\\n--header 'Content-Type: application/x-www-form-urlencoded' \\\n--data-urlencode 'amount=100' \\\n--data-urlencode 'transferType=DEPOSIT' \\\n--data-urlencode 'transferCode=1123' \\\n--data-urlencode 'comment=Comments' \\\n--data-urlencode 'requestSource=CRM'"
                }
              }
            }
          },
          "required": false,
          "x-send-file-in-body": false
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "servers": [
          {
            "url": "http://standalone.az-qa.com:81/dxweb/rest",
            "variables": {}
          }
        ]
      }
    },
    "/customers/si10016300/activateProfiles": {
      "put": {
        "tags": [
          "Misc"
        ],
        "summary": "activateProfiles",
        "operationId": "activateProfiles",
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "application/x-www-form-urlencoded"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/x-www-form-urlencoded": {
              "encoding": {},
              "schema": {
                "required": [
                  "allProfilesSet",
                  "activateProfilesSet"
                ],
                "type": "object",
                "properties": {
                  "allProfilesSet": {
                    "type": "string",
                    "description": "This profiles will be removed",
                    "example": "9276996:3"
                  },
                  "activateProfilesSet": {
                    "type": "string",
                    "description": "This profiles will be activated"
                  }
                }
              },
              "examples": {
                "JSON": {
                  "summary": "JSON",
                  "value": {
                    "allProfilesSet":"11342606:1,9276576: 2,36898725:1",
                    "activateProfilesSet":"11342606:1,9276576: 2"
                  }
                },
                "CURL": {
                  "summary": "CURL",
                  "value": "curl --location --request PUT '{{domain}}/dxweb/rest/customers/mk1104165/activateProfiles' \\\n--header 'Content-Type: application/x-www-form-urlencoded' \\\n--header 'Authorization: Basic cm9vdEBzeXN0ZW06cm9vdA==' \\\n--header 'Content-Type: application/x-www-form-urlencoded' \\\n--data-urlencode 'allProfilesSet=11342606:1,9276576: 2,36898725:1' \\\n--data-urlencode 'activateProfilesSet=11342606:1,9276576: 2'"
                }
              }
            }
          },
          "required": false,
          "x-send-file-in-body": false
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "servers": [
          {
            "url": "http://standalone.az-qa.com:81/dxweb/rest",
            "variables": {}
          }
        ]
      }
    },
    "/customers/si10016300/exchangeProfiles": {
      "put": {
        "tags": [
          "Misc"
        ],
        "summary": "exchangeProfiles",
        "operationId": "exchangeProfiles",
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "application/x-www-form-urlencoded"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/x-www-form-urlencoded": {
              "encoding": {},
              "schema": {
                "required": [
                  "profileAdd",
                  "profileRemove"
                ],
                "type": "object",
                "properties": {
                  "profileAdd": {
                    "type": "string"
                  },
                  "profileRemove": {
                    "type": "string"
                  }
                }
              },
              "examples": {
                "JSON": {
                  "summary": "JSON",
                  "value": {
                    "profileRemove":"11342606:1",
                    "profileAdd":""
                  }
                },
                "CURL": {
                  "summary": "CURL",
                  "value": "curl --location --request PUT '{{domain}}/dxweb/rest/customers/mk1104165/exchangeProfiles' \\\n--header 'Content-Type: application/x-www-form-urlencoded' \\\n--header 'Authorization: Basic cm9vdEBzeXN0ZW06cm9vdA==' \\\n--header 'Content-Type: application/x-www-form-urlencoded' \\\n--data-urlencode 'profileRemove=11342606:1' \\\n--data-urlencode 'profileAdd='"
                }
              }
            }
          },
          "required": false,
          "x-send-file-in-body": false
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "servers": [
          {
            "url": "http://standalone.az-qa.com:81/dxweb/rest",
            "variables": {}
          }
        ]
      }
    },
    "/withdrawal": {
      "get": {
        "tags": [
          "Misc"
        ],
        "summary": "validate/withdrawal",
        "operationId": "validate/withdrawal",
        "parameters": [
          {
            "name": "amount",
            "in": "query",
            "description": "",
            "required": true,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "number",
              "format": "double",
              "example": 238.9
            }
          },
          {
            "name": "requestSource",
            "in": "query",
            "description": "",
            "required": true,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "string",
              "example": "CRM"
            },
            "examples" : {
              "JSON" : {
                "summary" : "JSON",
                "value" : {
                  "amount":123.23,
                  "requestSource": "CRM"
                }
              },
              "CURL" : {
                "summary" : "CURL",
                "value" : "curl --location --request GET '{{domain}}/dxweb/rest/accounts/mk1104165/validate/withdrawal?amount=238.9&requestSource=CRM' \\\n--header 'Authorization: Basic cm9vdEBzeXN0ZW06cm9vdA=='"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {},
            "content": {
              "application/json": {
                "example": {
                  "valid": true,
                  "accountMetrics": {
                    "cashBalance": 8816656.74,
                    "margin": 146.020683399016,
                    "equity": 9053802.85,
                    "openPL": 237146.10418902,
                    "riskLevel": 1.6128105042514375E-5,
                    "reverseRiskLevel": 62003.56442148394,
                    "availableBalanceForWithdrawal": 8816656.74,
                    "activeBonuses": 0.0,
                    "liquidationLevel": null,
                    "marginLimitType": null,
                    "marginCoefficient": 1.0
                  }
                }
              }
            }
          }
        },
        "deprecated": false,
        "servers": [
          {
            "url": "http://standalone.az-qa.com:81/dxweb/rest/accounts/mk1116mm248/validate",
            "variables": {}
          }
        ]
      }
    },
    "/generateToken": {
      "get": {
        "tags": [
          "Misc"
        ],
        "summary": "generateToken",
        "operationId": "generateToken",
        "parameters": [
          {
            "name": "login",
            "in": "query",
            "description": "",
            "required": true,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "string",
              "example": "root"
            }
          },
          {
            "name": "domain",
            "in": "query",
            "description": "",
            "required": true,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "string",
              "example": "system"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "servers": [
          {
            "url": "http://standalone.az-qa.com:81/dxweb/rest",
            "variables": {}
          }
        ]
      }
    },
    "/accounts/mk1116248/validate/adjustment/negative": {
      "get": {
        "tags": [
          "Misc"
        ],
        "summary": "/validate/adjustment",
        "operationId": "/validate/adjustment",
        "parameters": [
          {
            "name": "amount",
            "in": "query",
            "description": "",
            "required": true,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "integer",
              "format": "int32",
              "example": 400
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {},
            "content": {
              "application/json": {
                "example": {
                  "causeLiquidation": false,
                  "expectedMarginLevel": 6204192.39,
                  "accountMetrics": {
                    "cashBalance": 8816656.74,
                    "margin": 145.92795769312,
                    "equity": 9053651.24,
                    "openPL": 236994.50141866,
                    "riskLevel": 1.611813331713007E-5,
                    "reverseRiskLevel": 62041.92385834266,
                    "availableBalanceForWithdrawal": 8816656.74,
                    "activeBonuses": 0.0,
                    "liquidationLevel": 50.0,
                    "marginLimitType": "REVERSE",
                    "marginCoefficient": 1.0
                  }
                }
              }
            }
          }
        },
        "deprecated": false,
        "servers": [
          {
            "url": "http://standalone.az-qa.com:81/dxweb/rest",
            "variables": {}
          }
        ]
      }
    },
    "/": {
      "get": {
        "tags": [
          "Misc"
        ],
        "summary": "accouns metrics",
        "operationId": "accounsmetrics",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {},
            "content": {
              "application/json": {
                "example": {
                  "cashBalance": 8816656.74,
                  "margin": 146.61611850912,
                  "equity": 9057189.72,
                  "openPL": 240532.97591036,
                  "riskLevel": 1.6187815762030876E-5,
                  "reverseRiskLevel": 61774.85676267315,
                  "availableBalanceForWithdrawal": 8816656.74,
                  "activeBonuses": 0.0,
                  "liquidationLevel": null,
                  "marginLimitType": null,
                  "marginCoefficient": 1.0
                }
              }
            }
          }
        },
        "deprecated": false
      }
    }
  },
  "components": {
    "securitySchemes": {
      "httpBasic": {
        "type": "http",
        "scheme": "basic"
      }
    }
  },
  "security": [
    {
      "httpBasic": []
    }
  ],
  "tags": [
    {
      "name": "Misc",
      "description": ""
    }
  ]
}
